language: node_js
node_js:
  - 10

before_install:
  - npm ci
  - npm run build
  - npm run start.ci
  - npm run mountebank.start.ci

script:
  - npm run unit.test.coverage
  - npm run unit.test.mutation
  - $(npm bin)/cypress run --record