language: node_js
node_js:
  - "node"
cache:
  # Caches $HOME/.npm when npm ci is default script command
  # Caches node_modules in all other cases
  npm: true
  directories:
    # we also need to cache folder with Cypress binary
    - ~/.cache

before_install:
  - sudo apt-get update
  - sudo apt -y install libgconf2.4
  - npm install
  - npm run build
  - npm run start.ci
  - npm run mountebank.start.ci

install:
  - npm ci

script:
  - npm run unit.test.coverage
  - npm run unit.test.mutation
  - npm run ui.test